###
# Get a specific doctor by ID
GET http://localhost:8083/doctors/550e8400-e29b-41d4-a716-446655440000
###

###
# Get a list of all doctors
GET http://localhost:8083/doctors
###

# Create a new doctor
POST http://localhost:8083/doctors
Content-Type: application/json

{
  "name": "Dr. Boy",
  "title": "Chirurgy"
}
###
# Update an existing doctor
PATCH http://localhost:8083/doctors/550e8400-e29b-41d4-a716-446655440001
Content-Type: application/json

{
  "name": "Updated Dr. Bill"
}
###

###
# Delete a doctor
DELETE http://localhost:8083/doctors/550e8400-e29b-41d4-a716-446655440002
###


